### ISSUE TITLE
Error running `docker-compose up`

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/toketi-iothub-to-cassandra#2]
Just pulled down the repo, edited the setup ps1 file and ran `docker-compose up` when I was hit with this error.

[ERROR] [07/06/2017 21:37:15.916] [default-akka.actor.default-dispatcher-3] [com.microsoft
.azure.iot.iothubreact.MessageFromDeviceSource] Fatal error: java.lang.NullPointerException, TrackingId: 560d1583-65cf-4
152-8b47-dd2ca5d0bcbd, at: 2017-07-06T21:37:15.915Z[GMT]
iothub2cassandra_service_1  | com.microsoft.azure.servicebus.ServiceBusException: java.lang.NullPointerException, Tracki
ngId: 560d1583-65cf-4152-8b47-dd2ca5d0bcbd, at: 2017-07-06T21:37:15.915Z[GMT]
iothub2cassandra_service_1  |   at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:
365)
iothub2cassandra_service_1  |   at java.lang.Thread.run(Thread.java:745)
iothub2cassandra_service_1  | Caused by: java.lang.NullPointerException
iothub2cassandra_service_1  |   at org.apache.qpid.proton.engine.impl.SaslImpl.plain(SaslImpl.java:446)
iothub2cassandra_service_1  |   at com.microsoft.azure.servicebus.amqp.ConnectionHandler.onConnectionBound(ConnectionHan
dler.java:74)
iothub2cassandra_service_1  |   at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:131)
iothub2cassandra_service_1  |   at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
iothub2cassandra_service_1  |   at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
iothub2cassandra_service_1  |   at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
iothub2cassandra_service_1  |   at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:
340)

It looks like there is an issue with the referenced version of the service bus sdk.  Has this been fixed in your upstream lib?

Thanks!

**Comment by dluc** [comment]
hi @WilliamBerryiii, it could also be a configuration problem. I've noticed some odd behavior with env vars set via Powershell.

Could you try setting the environment variables from Windows control panel, reopen the console and retry?

**Comment by WilliamBerryiii** [comment]
Ran the batch version in a std CMD prompt and can confirm they are set properly.  When I run `docker-compose up` however it looks like the compose file is not pulling the values.  Looking into it now.

**Comment by WilliamBerryiii** [comment]
Looks like the variable names for Access Policy were incorrect ... sorry I missed it!  I've made PRs for the fixes.
